# Generated by Django 6.0.6 on 2026-06-22 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('premium', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id_film', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=100)),
                ('genere', models.CharField(max_length=50)),
                ('durata', models.IntegerField()),
                ('anno_uscita', models.IntegerField()),
                ('regista', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Film',
            },
        ),
        migrations.CreateModel(
            name='Operatore',
            fields=[
                ('id_operatore', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('tipo_di_contratto', models.CharField(max_length=50)),
                ('data_assunzione', models.DateField()),
            ],
            options={
                'db_table': 'Operatore',
            },
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id_posto', models.AutoField(primary_key=True, serialize=False)),
                ('fila', models.CharField(max_length=5)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'Posto',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('nome_sala', models.CharField(max_length=50)),
                ('capienza', models.IntegerField()),
            ],
            options={
                'db_table': 'Sala',
            },
        ),
        migrations.CreateModel(
            name='Biglietto',
            fields=[
                ('id_biglietto', models.AutoField(primary_key=True, serialize=False)),
                ('data_acquisto', models.DateField()),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='cinema.cliente')),
                ('posto', models.ForeignKey(db_column='id_posto', on_delete=django.db.models.deletion.CASCADE, to='cinema.posto')),
            ],
            options={
                'db_table': 'Biglietto',
            },
        ),
        migrations.CreateModel(
            name='Acquisto',
            fields=[
                ('id_acquisto', models.AutoField(primary_key=True, serialize=False)),
                ('prezzo_biglietto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('metodo_pagamento', models.CharField(max_length=30)),
                ('biglietto', models.OneToOneField(db_column='id_biglietto', on_delete=django.db.models.deletion.CASCADE, to='cinema.biglietto')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='cinema.cliente')),
            ],
            options={
                'db_table': 'Acquisto',
            },
        ),
        migrations.AddField(
            model_name='posto',
            name='sala',
            field=models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, to='cinema.sala'),
        ),
        migrations.CreateModel(
            name='Spettacolo',
            fields=[
                ('id_spettacolo', models.AutoField(primary_key=True, serialize=False)),
                ('data_spettacolo', models.DateField()),
                ('ora_inizio', models.TimeField()),
                ('film', models.ForeignKey(db_column='id_film', on_delete=django.db.models.deletion.CASCADE, to='cinema.film')),
                ('operatore', models.ForeignKey(blank=True, db_column='id_operatore', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.operatore')),
                ('sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, to='cinema.sala')),
            ],
            options={
                'db_table': 'Spettacolo',
            },
        ),
        migrations.CreateModel(
            name='Gestione',
            fields=[
                ('id_gestione', models.AutoField(primary_key=True, serialize=False)),
                ('operatore', models.ForeignKey(db_column='id_operatore', on_delete=django.db.models.deletion.CASCADE, to='cinema.operatore')),
                ('spettacolo', models.ForeignKey(db_column='id_spettacolo', on_delete=django.db.models.deletion.CASCADE, to='cinema.spettacolo')),
            ],
            options={
                'db_table': 'Gestione',
            },
        ),
        migrations.AddField(
            model_name='biglietto',
            name='spettacolo',
            field=models.ForeignKey(db_column='id_spettacolo', on_delete=django.db.models.deletion.CASCADE, to='cinema.spettacolo'),
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id_recensione', models.AutoField(primary_key=True, serialize=False)),
                ('valutazione', models.IntegerField()),
                ('descrizione', models.TextField()),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='cinema.cliente')),
                ('film', models.ForeignKey(db_column='id_film', on_delete=django.db.models.deletion.CASCADE, to='cinema.film')),
            ],
            options={
                'db_table': 'Recensione',
                'unique_together': {('cliente', 'film')},
            },
        ),
    ]
